core:
  mode: "release"
  worker_num: 256
  queue_num: 512
  fail_fast_timeout: 3 # 当程序收到signal时候，要保证在fail_fast_timeout(unit: second)时间段内退出
  udp_port: 2000
  udp_read_buffer_size: 8388608
  udp_read_timeout: 3
  http_port: 3000
  log_size: 4096
  pid:
    enabled: false
    path: "logkafka.pid"
    override: true

api:
  stat_go_uri: "/api/stat/go"
  stat_app_uri: "/api/stat/app"
  config_uri: "/api/config"
  sys_stat_uri: "/sys/stats"
  app_log_uri: "/api/app/logs"

kafka:
  # 多个broker之间逗号分隔
  brokers: "127.0.0.1:9092"
  default_topic: "telemetry"
  http_topics:
    - http1
    - http2
